### ISSUE TITLE
Password contains special characters can not be login

### ISSUE THREAD

**Issue by livelazily** [Atelier-Shiori/MAL-Library#10]
Password contains special characters such as `$\):` always login faild

**Comment by chikorita157** [comment]
I have tried adding those characters $\): to my password and it seems to not to work at all.

2017-10-26 20:41:13.865231-0400 MAL Library[2786:13516448] Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={NSLocalizedDescription=Request failed: unauthorized (401), NSErrorFailingURLKey=https://myanimelist.net/api/account/verify_credentials.xml, com.alamofire.serialization.response.error.data=<496e7661 6c696420 63726564 656e7469 616c73>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x604000032260> { URL: https://myanimelist.net/api/account/verify_credentials.xml } { status code: 401, headers {
    "Cache-Control" = "no-cache";
    "Content-Encoding" = gzip;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Fri, 27 Oct 2017 00:41:13 GMT";
    Server = Apache;
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload";
    Vary = "Accept-Encoding";
    "Www-Authenticate" = "Basic realm=\"MyAnimeList API\"";
} }}

When I tried it in hurl it:
HEADERS

Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Fri, 27 Oct 2017 00:42:10 GMT
Server: Apache
Set-Cookie: MALSESSIONID=q08rnome07l3lud2137tda4o81; expires=Mon, 25-Oct-2027 00:42:10 GMT; Max-Age=315360000; path=/; secure; HttpOnly, MALHLOGSESSID=b01f8b15cab0b2f4c57b3eb583e1a7f6; expires=Wed, 26-Oct-2022 00:42:10 GMT; Max-Age=157680000; path=/
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Transfer-Encoding: chunked
Vary: Accept-Encoding
Www-Authenticate: Basic realm="MyAnimeList API"
BODY view raw

Invalid credentials

It may have to do something with this: https://myanimelist.net/forum/?topicid=1677587 that broke it since I cannot log in anymore. I will let them know.

**Comment by livelazily** [comment]
Password contains `$\):` can login the website normaly
This passwords often generate by something like keepassxc or lastpass

**Comment by chikorita157** [comment]
It seems to not work on the API side then... Here is the full request from hurl.it:

 401 Unauthorized       19 bytes       516 ms

View Request View Response
HEADERS

Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Fri, 27 Oct 2017 00:42:10 GMT
Server: Apache
Set-Cookie: MALSESSIONID=q08rnome07l3lud2137tda4o81; expires=Mon, 25-Oct-2027 00:42:10 GMT; Max-Age=315360000; path=/; secure; HttpOnly, MALHLOGSESSID=b01f8b15cab0b2f4c57b3eb583e1a7f6; expires=Wed, 26-Oct-2022 00:42:10 GMT; Max-Age=157680000; path=/
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Transfer-Encoding: chunked
Vary: Accept-Encoding
Www-Authenticate: Basic realm="MyAnimeList API"
BODY view raw

Invalid credentials

**Comment by chikorita157** [comment]
After investigation, characters like $ \ ) will work. : will not. I notice that in 1Password, the password generator from there will never use the character : (colon). This is probably a limitation with the API that you should report to MAL Support.

Instead of : (colon), use ; (semi colon) instead.

**Comment by chikorita157** [comment]
I recieved a response. MyAnimeList support will look at this.

> Hello James,
> 
> Thank you for contact with MAL Support Team.
> 
> We really appreciate your feedback on the API  not accepting a password containing a colon (:). 
> I am sending your feedback to the developers, and I'll make sure that your voice will be heard and considered for further updates on the website.
> 
> Please be assured that we make every effort to provide better service and a supreme experience for you within MyAnimeList. 
> 
> Should you have other concerns, do not hesitate to contact us again!
> 
> For the MyAnimeList Support Team it is always a pleasure to assist you.
> 
> Sincerely,
> 
> Makenna
> 

This issue will be closed. If I have any update, I will update this.
