### ISSUE TITLE
Light Novels show under Manga section

### ISSUE THREAD

**Issue by fieldhouse** [Atelier-Shiori/MAL-Library#11]
Would be awesome to either have an indicator showing that it's a LN or a different section so when you search for a title you don't have to guess which one is the Manga and which is the LN.

**Comment by chikorita157** [comment]
I added a type column in the search view for Manga and remove the status columns (since they are redundant as the filters will act like tabs by default now) and replaced it as a type column. If this is acceptable, please reply.

![2017-12-04_10-59-40](https://user-images.githubusercontent.com/161183/33562116-61fc3d06-d8e2-11e7-89e5-99f3309c37d9.png)
![2017-12-04_10-42-34](https://user-images.githubusercontent.com/161183/33562119-64e99694-d8e2-11e7-9970-f9f1a1947921.png)

**Comment by fieldhouse** [comment]
yeah, I think that works well.  Thanks for looking into it.
