### ISSUE TITLE
increasing chapters over 100 reverts to 100

### ISSUE THREAD

**Issue by fieldhouse** [Atelier-Shiori/MAL-Library#12]
not a huge issue, just noticed that if a manga has over 100 issue that if I edit it and use the up arrow, the number jumps back to 100 

example: edit a manga, currently lists read up through 104, hit up arrow, expect it to go to 105, it goes to 100.

**Comment by chikorita157** [comment]
The steppers for the chapters/volumes and episodes when there is no totals for them doesn't work. I have to set the max values on the stepper as it wasn't being set, only to the fields.

Fixed with https://github.com/Atelier-Shiori/MAL-Library/commit/2d44f9dea5810a1ec62f9c8c8c9a6b7c040ce7c9. Will be adding the fix to the stable branch and release a fix along with out bug fixes.
